    let box = document.getElementById("box");
    console.log(box);
    box.style.backgroundColor = "yellow";
    box.style.margin = "20px";
    box.style.padding = "10px";
    box.style.height = "200px";
    box.style.width =  "300px";
    box.style.fontSize = "18px";
    box.style.fontWeight = "bold";
    box.style.color = "blue";